name: Deploy to EC2 using dockerHub and CodeDeploy

on:
   push:
     branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: npm install
        run: npm ci
        
      - name: Unit test start
        run: npm test
        env:
          dbUrl: ${{ secrets.dbUrl }}

      # - name: Login to docker hub
      #   if: success()
      #   uses: actions-hub/docker/login@master
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      # - name: Build image
      #   if: success()
      #   run: docker build --tag ${{ secrets.hubName }}:latest .

      # - name: Push to docker registry
      #   if: success()
      #   uses: actions-hub/docker@master
      #   with:
      #     args: push ${{ secrets.hubName }}:latest

      # - name: run codeDeploy
      #   run: aws deploy --region ap-northeast-2 create-deployment --application-name codedeploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name gropu --github-location repository=gyim1345/snsAPI,commitId=${GITHUB_SHA}
      #   env:
      #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #       Default_region_name: ap-northeast-2
   

          